const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIES_REQUEST: 'FETCH_MOVIES_REQUEST',
    FETCH_MOVIES_ERROR: 'FETCH_MOVIES_ERROR',
    FETCH_MOVIE: 'FETCH_MOVIE',
    FETCH_MOVIE_REQUEST: 'FETCH_MOVIE_REQUEST',
    FETCH_MOVIE_ERROR: 'FETCH_MOVIE_ERROR',
    SET_MOVIE: 'SET_MOVIE',
    SUBMIT_REVIEW: 'SUBMIT_REVIEW',
    SEARCH_MOVIES: 'SEARCH_MOVIES',
    SEARCH_MOVIES_REQUEST: 'SEARCH_MOVIES_REQUEST',
    SEARCH_MOVIES_ERROR: 'SEARCH_MOVIES_ERROR'
}

export default Constants;